pipeline {
  agent any
  
  stages {
    stage ('Compile Stage') {
      steps {
        withMaven(maven : 'Maven-3.0.5') {
          sh 'mvn clean compile'
        }
      }
    }
    stage ('Test Stage') {
      steps {
        withMaven(maven : 'Maven-3.0.5') {
          sh 'mvn test'
        }
      }
    }
    stage ('Deployment Stage') {
      steps {
        withMaven(maven : 'Maven-3.0.5') {
          sh 'mvn clean deploy'
        }
      }
    }
    
  }
}
